### PR TITLE
Add user expiration and device limit

### PR DESCRIPTION
**Pull request by tananaev**
@Abyss777, can you please review the changes.

### CODE REVIEW

**Comment by Abyss777** [comment]
Looks good for me.
I liked idea that user can see his expiration date and device limit.

One wish is say to user somehow that he can be expired/disabled. May be make `Strings.loginFailed` something like this:
"Incorrect email address/password or user disabled/expired"

**Comment by tananaev** [comment]
Fixed this one as well. Expired and disabled accounts are now general errors.

**Comment by Abyss777** [comment]
Here is new problem:
It happen after user disabling and page refresh.

image

I think login screen won't appear until cookies will be cleared.

**Comment by tananaev** [comment]
I noticed it as well. You can't even logout, but I think it's a very rare case when you get locked in the middle of the session, so I don't think we need to handle this case.

**Comment by tananaev** [comment]
What do you think?

**Pull request merged**
