### PR TITLE
Improve Notifications dialog and controller

### PR DESCRIPTION
**Pull request by Abyss777**
There are two reasons:

1. Redo it in simple and more correct way
2. Make it work on ExtJS 6.2.0

### CODE REVIEW

**Comment by tananaev** [comment]
Is it that easy? Looks great, thanks.

**Comment by Abyss777** [comment]
Yes. I wrote it then was not experienced in ExtJS. It was too complicated.
`mapping` simplified everything and allowed to remove confusing 6.2.0 code.

**Comment by tananaev** [comment]
Are there any other places that we can simplify using mapping?

**Comment by Abyss777** [comment]
Not in that way. We use "known" attributes nowhere at the moment except notifications. Also want to note that mapping is one direction. Changing mapping 'attributes.web` does not change 'attributes[web]'. 

But I know one place where we can use it:
Add columns to route report grid with some common attributes.

**Comment by tananaev** [comment]
For example distance. Anyway, thanks for pull request again.

**Pull request merged**
