### PR TITLE
Add "Animal" device category

### PR DESCRIPTION
**Pull request by Abyss777**
Added new category as you suggested here https://www.traccar.org/forums/topic/additional-icons-and-current-location/

image

### CODE REVIEW

**Comment by tananaev** [comment]
Looks great, merged.

I was wondering if we can combine all images in a single XML file. Maybe it will reduce the download time and increase speed? Do you think it makes sense?

**Comment by Abyss777** [comment]
Not sure if it gives any benefits, they are mostly loaded in parallel:
image

But may be we should research it.

**Comment by tananaev** [comment]
Maybe we can just keep it in mind if we have any performance issues at some point in future.

**Comment by Abyss777** [comment]
Sure, it is not hard to combine it.

**Pull request merged**
