### PR TITLE
Save cookie credentials in base64

### LINKED ISSUE #419: Remembered password saved incorrectly
Chars in password are replaced by html codes in cookie store, for example `pa$$word` by `pa%24%24word`. 

image

And then passed to server as is and login fails.

image

### PR DESCRIPTION
**Pull request by Abyss777**
fix #419 and web part for https://github.com/tananaev/traccar/pull/2973

### CODE REVIEW

**Comment by tananaev** [comment]
Merged.

By the way, what would happen if someone has old cookies from previous version?

**Comment by Abyss777** [comment]
Authentication will fail (otherwise user exists in DB with email and password equal base64 of original) and user will be asked for user/password again.

**Comment by tananaev** [comment]
That OK. I just wanted make sure that it won't keep trying to use invalid data over and over.

**Comment by Abyss777** [comment]
Frankly it will try, but not every time, just if there is no session on the server (after server restart).
May be also add clear cookies on login fail?

**Comment by tananaev** [comment]
I think it's fine as it is, as long as it still asks for regular login.

**Pull request merged**
