### PR TITLE
Update Json

### PR DESCRIPTION
**Pull request by rospus**
Finished translating records still in english and some minor fixes in old italian translation.

### CODE REVIEW

**Comment by tananaev** [comment]
I appreciate the effort, but all localization should be done via Transifex:

https://www.transifex.com/traccar/traccar/

Please update translations there.

**Comment by rospus** [comment]
Sorry, didn't realize it was on Transifex. I'll update it probably tomorrow.
Thanks for pointing me.

Alessandro

Il mar 24 gen 2017 22:11 Anton Tananaev <notifications@github.com> ha
scritto:

**Comment by rospus** [comment]
Hi Anton, I finished translating (many records were erroneously translated
English to English), fixed several typos and homogenized usage of some
terms.
I gave an overall look and italian translation seems ok now.

Alessandro


2017-01-24 22:11 GMT+01:00 Anton Tananaev <notifications@github.com>:

**Comment by tananaev** [comment]
Thanks. All the translations on GitHub will be updated in batch with the next release.

**Pull request closed without merging**
