### PR TITLE
Resource to copy (CTRL + C) the informations available in the STATUS table.

### PR DESCRIPTION
**Pull request by Turbovix**
The inserted code lines enable the copy (CTRL + C) of the information sent by the trackers and available in the STATUS table.

### CODE REVIEW

**Comment by tananaev** [comment]
What does it look like? Are there any differences in the UI, or it just makes it possible to use copy/paste?

**Comment by Turbovix** [comment]
Anton, there is no change in the UI. It only enables marking the information to copy via the right mouse button or via CTRL + C!

**Comment by tananaev** [comment]
I think it makes sense to enable it for all grids. I suggest that we create a base class where we can configure it.

**Comment by Turbovix** [comment]
screenshot_20170628_001225

**Comment by tananaev** [comment]
Closing this as #603 is merged.

**Pull request closed without merging**
