### PR TITLE
Implement Events panel

### PR DESCRIPTION
**Pull request by Abyss777**
Implemented Events panel on the right side for desktop and in the same manner as reports for mobile.

- Moved Sound toggle to Events panel to save space in mobile view.
- Formatted time as for devices and make formatter ordinary.
- Make `Event.text` calculated field
- Added switch to always scroll on the last event (last is down)
- Made panel stateful

Default View
image

Events panel are showed
image

### CODE REVIEW

**Comment by tananaev** [comment]
Looks good. Have you checked if it conflicts with anything else that uses "Events" store?

**Comment by Abyss777** [comment]
Oh, missed one place, where it is used. But I'm not sure feature it is or bug. It is used when we pass `eventId` via URL parameter.
image

If it is not OK, I can implement `LastEvents` store for this.

**Comment by tananaev** [comment]
I think it's fine. I'll merge the code then.

**Comment by tananaev** [comment]
Thanks for pull request.

**Pull request merged**
