### PR TITLE
Added .gitignore and /nbproject to .gitignore;

### PR DESCRIPTION
**Pull request by jon-stumpf**

### CODE REVIEW

**Comment by tananaev** [comment]
Why are you adding `.gitignore` to the list?

**Comment by jon-stumpf** [comment]
It doesn't need to be.  Force of habit.

**Comment by tananaev** [comment]
I don't think it makes sense. It means that you won't be able to modify `.gitignore` file itself. Am I missing something? What is the purpose?

**Comment by jon-stumpf** [comment]
I will remove the pull request.

**Comment by tananaev** [comment]
If you want we can include `nbproject` to the git ignore file. Is it a folder/file created by NetBeans?

**Comment by jon-stumpf** [comment]
Correct.

**Comment by tananaev** [comment]
Please update your pull request.

**Comment by jon-stumpf** [comment]
Closed due to orthogonal commits.  Opened new pull request.

**Pull request closed without merging**
